### ISSUE TITLE
What's Style trumps?

### ISSUE THREAD

**Issue by doggy8088** [csswizardry/CSS-Guidelines#14]
Hi,

What's the "Style trumps" mean?  Can you describe more about this?  I'm not really understanding about this. 

Thanks!

BR,
Will

**Comment by nikglavin** [comment]
From my understanding style trumps would be similar to a generic state in SMACSS (Low specificity that relies on cascade to overwrite the component's style)

```
<div class="component">
    <div class="component__element is-error"></div>
</div>
```

is-error would be at the bottom of the style sheet and would overwrite (Trump) a particular style on component__element by cascade rather than specificity 

```
.component__element {
  color: blue;
}
....
.is-error {
  color: red;
}
```

Cheers
Nick

**Comment by doggy8088** [comment]
Thanks :)

**Comment by csswizardry** [comment]
From [the Wikipedia page](http://en.wikipedia.org/wiki/Trump):

> … these cards then outrank all cards of plain (non-trump) suits.

If we replace _card_ with _selector_, we can see how these selectors are meant to override, or trump, any others :)
